fo=open("abc.txt","w")
print("Name of the file:",fo.name)
print("Closed or not:",fo.closed)
print("opening mode:",fo.mode)
fo.write("Programming with python is Fun")
#print("Softspace flag:",fo.softspace)
fo.write("\n hello python")
fo.write("\n Programming in Java is more Fun")
fo.close()
